### ISSUE TITLE
Week 8 Ready for Review

### ISSUE THREAD

**Issue by SapphireStar31** [SapphireStar31/week-8-RESTful-APIs#1]
@pawaitemadisoncollege
What were your key learning points/takeaways?
My key learning points this week were what exactly is an API, how to use an API, and then be able to tie it into my own code.

What challenged you?
I don't think anything really challenged me this week since the videos explained things in a way so I understood what was happening.

What problems did you solve and what resources did you use to solve them?
I just a had a problem with my imports with jackson showing it was wrong, but that went away after like 20min of letting it sit and me moving to something else and then coming back and seeing they were finally correct. Not sure why it was doing that since everything was correct and tests pass even if they were red.

**Comment by pawaitemadisoncollege** [comment]
Hi @SapphireStar31!  It looks like you got in some good practice consuming a restful api with java code and unit testing the client dao that you wrote.  This should lay the foundation for consuming an api in your indie project.

A couple things related to best practices:

- [ ] When implementing in a real application, the endpoint is best placed in a properties file for easy updating with out a source code change: https://github.com/SapphireStar31/week-8-RESTful-APIs/blob/32977d7fd0d283a64244660f970c69ff1d4ff4d4/src/main/java/persistence/PetAPIDao.java#L16
- [ ] This method would be better if it accepted a pet id as a parameter, rather than hard coding the 3 in the endpoint/url here: https://github.com/SapphireStar31/week-8-RESTful-APIs/blob/32977d7fd0d283a64244660f970c69ff1d4ff4d4/src/main/java/persistence/PetAPIDao.java#L16

Week 8: met
